import { generatePermissionManifest } from "@umbraco-workflow/core";
import {
  WORKFLOW_USER_PERMISSION_ALTERNATEVERSION_CREATE,
  WORKFLOW_USER_PERMISSION_ALTERNATEVERSION_DELETE,
  WORKFLOW_USER_PERMISSION_ALTERNATEVERSION_PROMOTE,
  WORKFLOW_USER_PERMISSION_ALTERNATEVERSION_READ,
  WORKFLOW_USER_PERMISSION_ALTERNATEVERSION_UPDATE,
} from "./constants.js";

const data = [
  WORKFLOW_USER_PERMISSION_ALTERNATEVERSION_CREATE,
  WORKFLOW_USER_PERMISSION_ALTERNATEVERSION_READ,
  WORKFLOW_USER_PERMISSION_ALTERNATEVERSION_UPDATE,
  WORKFLOW_USER_PERMISSION_ALTERNATEVERSION_DELETE,
  WORKFLOW_USER_PERMISSION_ALTERNATEVERSION_PROMOTE,
].map((verb) =>
  generatePermissionManifest({ verb, group: "Alternate Version" })
);

export const manifests = data;
