import { generatePermissionManifest } from "@umbraco-workflow/core";
import {
  WORKFLOW_USER_PERMISSION_RELEASESET_CREATE,
  WORKFLOW_USER_PERMISSION_RELEASESET_READ,
  WORKFLOW_USER_PERMISSION_RELEASESET_DELETE,
  WORKFLOW_USER_PERMISSION_RELEASESET_UPDATE,
  WORKFLOW_USER_PERMISSION_RELEASESET_PUBLISH,
} from "./constants.js";

const data = [
  WORKFLOW_USER_PERMISSION_RELEASESET_CREATE,
  WORKFLOW_USER_PERMISSION_RELEASESET_READ,
  WORKFLOW_USER_PERMISSION_RELEASESET_UPDATE,
  WORKFLOW_USER_PERMISSION_RELEASESET_DELETE,
  WORKFLOW_USER_PERMISSION_RELEASESET_PUBLISH,
].map((verb) => generatePermissionManifest({ verb, group: "Release Set" }));

export const manifests = data;
