import {
  WORKFLOW_USER_PERMISSION_APPROVALGROUP_READ,
  WORKFLOW_USER_PERMISSION_APPROVALGROUP_CREATE,
  WORKFLOW_USER_PERMISSION_APPROVALGROUP_UPDATE,
  WORKFLOW_USER_PERMISSION_APPROVALGROUP_DELETE,
} from "./constants.js";
import { generatePermissionManifest } from "@umbraco-workflow/core";

const data = [
  WORKFLOW_USER_PERMISSION_APPROVALGROUP_CREATE,
  WORKFLOW_USER_PERMISSION_APPROVALGROUP_READ,
  WORKFLOW_USER_PERMISSION_APPROVALGROUP_UPDATE,
  WORKFLOW_USER_PERMISSION_APPROVALGROUP_DELETE,
].map((verb) => generatePermissionManifest({ verb, group: "Approval Group" }));

export const manifests = data;
