export const constants = {
  workflow: "workflow",
  events: {
    workflowAction: "workflowAction", // signalr
    workflowActioned: "workflowActioned", // angularjs
    workflowDetail: "workflowDetail",
    workflowAppActive: "workflowAppActive",
    contentReviewsSettingsUpdated: "contentReviews.settingsUpdated",
    buttonStateChanged: "buttonStateChanged",
    configSaved: "configSaved",
    contentSaved: "content.saved",
    contentUnpublished: "content.unpublished",
    appTabChange: "app.tabChange",
    editorsOpen: "appState.editors.open",
    editorClose: "appState.editors.close",
    refreshGroups: "refreshGroups",
    goToNode: "goToNode",
  },
  actions: {
    publish: "publish",
    unpublish: "unpublish",
    initiate: "initiate",
    cancel: "cancel",
    reject: "reject",
    save: "save",
    saveAndPublish: "saveAndPublish",
    schedulePublish: "schedulePublish",
    publishDescendant: "publishDescendant",
    sendToPublish: "sendToPublish",
  },
  sizes: {
    s: "small",
    m: "medium",
    l: "large",
  },
  states: {
    success: "success",
    error: "failed",
    busy: "waiting",
    init: "init",
    rejected: "rejected",
    detail: "detail",
    published: "published",
    draft: "draft",
  },
  invariantCulture: "*",
};
